USE [master]

/****** Object:  Database [HomemadeEats]    Script Date: 3/2/2016 10:05:48 AM ******/
CREATE DATABASE [HomemadeEats]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HomemadeEats', FILENAME = N'C:\DevelopmentProjects_DB\SQL2014\MSSQL12.SQL2014\MSSQL\DATA\HomemadeEats.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HomemadeEats_log', FILENAME = N'C:\DevelopmentProjects_DB\SQL2014\MSSQL12.SQL2014\MSSQL\DATA\HomemadeEats_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)


ALTER DATABASE [HomemadeEats] SET COMPATIBILITY_LEVEL = 120


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HomemadeEats].[dbo].[sp_fulltext_database] @action = 'enable'
end


ALTER DATABASE [HomemadeEats] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [HomemadeEats] SET ANSI_NULLS OFF 


ALTER DATABASE [HomemadeEats] SET ANSI_PADDING OFF 


ALTER DATABASE [HomemadeEats] SET ANSI_WARNINGS OFF 


ALTER DATABASE [HomemadeEats] SET ARITHABORT OFF 


ALTER DATABASE [HomemadeEats] SET AUTO_CLOSE OFF 


ALTER DATABASE [HomemadeEats] SET AUTO_SHRINK ON 


ALTER DATABASE [HomemadeEats] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [HomemadeEats] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [HomemadeEats] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [HomemadeEats] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [HomemadeEats] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [HomemadeEats] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [HomemadeEats] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [HomemadeEats] SET  DISABLE_BROKER 


ALTER DATABASE [HomemadeEats] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [HomemadeEats] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [HomemadeEats] SET TRUSTWORTHY OFF 


ALTER DATABASE [HomemadeEats] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [HomemadeEats] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [HomemadeEats] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [HomemadeEats] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [HomemadeEats] SET RECOVERY SIMPLE 


ALTER DATABASE [HomemadeEats] SET  MULTI_USER 


ALTER DATABASE [HomemadeEats] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [HomemadeEats] SET DB_CHAINING OFF 


ALTER DATABASE [HomemadeEats] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [HomemadeEats] SET TARGET_RECOVERY_TIME = 0 SECONDS 


ALTER DATABASE [HomemadeEats] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [HomemadeEats] SET  READ_WRITE 



